# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'marvelapp_start' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  plugin 'cocoapods-keys', {
    :project => "Marvel",
    :keys => [
      "MarvelApiKey",
      "MarvelPrivateKey"
    ]
  }

  # Pods for marvelapp_start
  pod 'SwiftGen'
  pod 'RxSwift', '~> 4.5'
  pod 'Moya/RxSwift','~> 12.0.1'
  pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/ivanbruel/Moya-ObjectMapper'
  pod 'CryptoSwift'
  pod 'Dollar'

end
